### ISSUE TITLE
Customer Care Solution

### ISSUE THREAD

**Issue by megankweil** [megankweil/Use-Cases#1]
# Description
- A customer has reached out to a brand for help - could be online, IVR (never reached a person, IVR -> live call), web chat - how do you take advantage of this opportunity to engage the customer in a valuable way? 
- Channels could include - IVR, Call Center Agent Discussion, Webchat

## Action required
- [ ] [Review AT&T Intercept study](https://sundaysky-my.sharepoint.com/personal/megan_weil_sundaysky_com/_layouts/15/guestaccess.aspx?docid=12db5d5429e3c41739ff2f593737ae733&authkey=AST227A38DhSAI0zR5Bn_EU)
- [ ] Persona definition by industry - Telco-MSO, Telco-Wireless, FS-Banking, FS-CC
- [ ] Scenario definition for each persona including possible motivations for reaching out to Brand for help
- [ ] Survey to validate/define user value
- [ ] In-person focus group
- [ ] Customer pitch 

## Customer Prospects
- Amex
- AT&T
